subroutine smod
use fdeclarations

implicit none

do i=1,n
b(i,1)=min(cuvlow(i),cdvshallow(i),sand(i))
g(i,1)=min(cuhigh(i),cdshallow(i),boulders(i))
g(i,2)=min(cuhigh(i),cdshallow(i),lg(i))
g(i,3)=min(cuhigh(i),cdshallow(i),ls(i))
g(i,4)=min(cuhigh(i),cdshallow(i),ss(i))
g(i,5)=min(cuhigh(i),cdvshallow(i),ls(i))
g(i,6)=min(cuhigh(i),cdmoderate(i),ls(i))
g(i,7)=min(cuhigh(i),cdmoderate(i),ss(i))
g(i,8)=min(culow(i),cdshallow(i),boulders(i))
g(i,9)=min(culow(i),cdshallow(i),lg(i))
g(i,10)=min(culow(i),cdshallow(i),ls(i))
g(i,11)=min(culow(i),cdshallow(i),mg(i))
g(i,12)=min(culow(i),cdshallow(i),ss(i))
g(i,13)=min(culow(i),cdvshallow(i),lg(i))
g(i,14)=min(culow(i),cdvshallow(i),ls(i))
g(i,15)=min(culow(i),cdmoderate(i),ss(i))
g(i,16)=min(cuvhigh(i),cdshallow(i),lg(i))
g(i,17)=min(cuvlow(i),cdshallow(i),lg(i))
g(i,18)=min(cuvlow(i),cdshallow(i),ls(i))
g(i,19)=min(cuvlow(i),cdshallow(i),silt(i))
g(i,20)=min(cuvlow(i),cdshallow(i),lg(i))
g(i,21)=min(cuvlow(i),cdvshallow(i),ls(i))
g(i,22)=min(cuvlow(i),cdmoderate(i),lg(i))
g(i,23)=min(cumoderate(i),cdshallow(i),lg(i))
g(i,24)=min(cumoderate(i),cdshallow(i),ls(i))
g(i,25)=min(cumoderate(i),cdshallow(i),ss(i))
g(i,26)=min(cumoderate(i),cdvshallow(i),ss(i))
h(i,1)=min(cuvhigh(i),cdshallow(i),ss(i))
h(i,2)=min(cumoderate(i),cdshallow(i),boulders(i))
h(i,3)=min(cumoderate(i),cdvshallow(i),boulders(i))
h(i,4)=min(cumoderate(i),cdvshallow(i),lg(i))
m(i,1)=min(cuhigh(i),cdvshallow(i),ss(i))
m(i,2)=min(cuhigh(i),cdmoderate(i),boulders(i))
m(i,3)=min(culow(i),cddeep(i),boulders(i))
m(i,4)=min(culow(i),cdshallow(i),fg(i))
m(i,5)=min(culow(i),cdvdeep(i),ls(i))
m(i,6)=min(culow(i),cdvshallow(i),boulders(i))
m(i,7)=min(culow(i),cdvshallow(i),mg(i))
m(i,8)=min(culow(i),cdvshallow(i),ss(i))
m(i,9)=min(culow(i),cdmoderate(i),boulders(i))
m(i,10)=min(culow(i),cdmoderate(i),lg(i))
m(i,11)=min(culow(i),cdmoderate(i),ls(i))
m(i,12)=min(cuvhigh(i),cdshallow(i),boulders(i))
m(i,13)=min(cuvhigh(i),cdshallow(i),ls(i))
m(i,14)=min(cuvhigh(i),cdvshallow(i),sand(i))
m(i,15)=min(cuvhigh(i),cdmoderate(i),lg(i))
m(i,16)=min(cuvhigh(i),cdmoderate(i),ls(i))
m(i,17)=min(cuvlow(i),cddeep(i),boulders(i))
m(i,18)=min(cuvlow(i),cdshallow(i),boulders(i))
m(i,19)=min(cuvlow(i),cdshallow(i),mg(i))
m(i,20)=min(cuvlow(i),cdshallow(i),ss(i))
m(i,21)=min(cuvlow(i),cdvshallow(i),boulders(i))
m(i,22)=min(cuvlow(i),cdmoderate(i),boulders(i))
m(i,23)=min(cuvlow(i),cdmoderate(i),fg(i))
m(i,24)=min(cuvlow(i),cdmoderate(i),ls(i))
m(i,25)=min(cuvlow(i),cdmoderate(i),sand(i))
m(i,26)=min(cumoderate(i),cddeep(i),ss(i))
m(i,27)=min(cumoderate(i),cddeep(i),lg(i))
m(i,28)=min(cumoderate(i),cdshallow(i),mg(i))
m(i,29)=min(cumoderate(i),cdvshallow(i),ls(i))
m(i,30)=min(cumoderate(i),cdmoderate(i),lg(i))
m(i,31)=min(cumoderate(i),cdmoderate(i),ls(i))
m(i,32)=min(cumoderate(i),cdmoderate(i),ss(i))
p(i,1)=min(cuhigh(i),cdmoderate(i),lg(i))
p(i,2)=min(culow(i),cddeep(i),ss(i))
p(i,3)=min(culow(i),cdvdeep(i),lg(i))
p(i,4)=min(cuvhigh(i),cdshallow(i),mg(i))
p(i,5)=min(cuvhigh(i),cdvshallow(i),fg(i))
p(i,6)=min(cuvhigh(i),cdmoderate(i),boulders(i))
p(i,7)=min(cuvhigh(i),cdmoderate(i),ss(i))
p(i,8)=min(cuvlow(i),cddeep(i),ls(i))
p(i,9)=min(cuvlow(i),cdshallow(i),fg(i))
p(i,10)=min(cuvlow(i),cdshallow(i),sand(i))
p(i,11)=min(cuvlow(i),cdmoderate(i),mg(i))

good=maxval(g, dim=2)
moderate=maxval(m, dim=2)
high=maxval(h, dim=2)
poor=maxval(p, dim=2)
bad=maxval(b, dim=2)
end do

end subroutine smod
