subroutine sopt
use fdeclarations

implicit none

do i=1,n
b3(i,1)=min(cuvlow(i),cdvshallow(i),sand(i))
g3(i,1)=min(cuhigh(i),cdshallow(i),lg(i))
g3(i,2)=min(cuhigh(i),cdmoderate(i),ls(i))
g3(i,3)=min(cuhigh(i),cdmoderate(i),ss(i))
g3(i,4)=min(culow(i),cdshallow(i),mg(i))
g3(i,5)=min(culow(i),cdvshallow(i),ss(i))
g3(i,6)=min(culow(i),cdmoderate(i),boulders(i))
g3(i,7)=min(cuvhigh(i),cdshallow(i),lg(i))
g3(i,8)=min(cuvlow(i),cdshallow(i),fg(i))
g3(i,9)=min(cuvlow(i),cdvshallow(i),boulders(i))
g3(i,10)=min(cuvlow(i),cdvshallow(i),lg(i))
g3(i,11)=min(cuvlow(i),cdmoderate(i),boulders(i))
g3(i,12)=min(cuvlow(i),cdmoderate(i),lg(i))
g3(i,13)=min(cumoderate(i),cdvshallow(i),ls(i))
g3(i,14)=min(cumoderate(i),cdmoderate(i),ls(i))
h3(i,1)=min(cuhigh(i),cdshallow(i),boulders(i))
h3(i,2)=min(cuhigh(i),cdshallow(i),ls(i))
h3(i,3)=min(cuhigh(i),cdshallow(i),ss(i))
h3(i,4)=min(cuhigh(i),cdvshallow(i),ls(i))
h3(i,5)=min(culow(i),cdshallow(i),boulders(i))
h3(i,6)=min(culow(i),cdshallow(i),lg(i))
h3(i,7)=min(culow(i),cdshallow(i),ls(i))
h3(i,8)=min(culow(i),cdshallow(i),ss(i))
h3(i,9)=min(culow(i),cdvshallow(i),lg(i))
h3(i,10)=min(culow(i),cdvshallow(i),ls(i))
h3(i,11)=min(culow(i),cdmoderate(i),ls(i))
h3(i,12)=min(culow(i),cdmoderate(i),ss(i))
h3(i,13)=min(cuvhigh(i),cdshallow(i),ls(i))
h3(i,14)=min(cuvhigh(i),cdshallow(i),ss(i))
h3(i,15)=min(cuvhigh(i),cdmoderate(i),ls(i))
h3(i,16)=min(cuvlow(i),cdshallow(i),boulders(i))
h3(i,17)=min(cuvlow(i),cdshallow(i),lg(i))
h3(i,18)=min(cuvlow(i),cdshallow(i),ls(i))
h3(i,19)=min(cuvlow(i),cdshallow(i),mg(i))
h3(i,20)=min(cuvlow(i),cdshallow(i),ss(i))
h3(i,21)=min(cuvlow(i),cdvshallow(i),ls(i))
h3(i,22)=min(cumoderate(i),cdshallow(i),boulders(i))
h3(i,23)=min(cumoderate(i),cdshallow(i),lg(i))
h3(i,24)=min(cumoderate(i),cdshallow(i),ls(i))
h3(i,25)=min(cumoderate(i),cdshallow(i),ss(i))
h3(i,26)=min(cumoderate(i),cdvshallow(i),boulders(i))
h3(i,27)=min(cumoderate(i),cdvshallow(i),lg(i))
h3(i,28)=min(cumoderate(i),cdvshallow(i),ss(i))
h3(i,29)=min(cumoderate(i),cdmoderate(i),ss(i))
m3(i,1)=min(cuhigh(i),cdvshallow(i),ss(i))
m3(i,2)=min(cuhigh(i),cdmoderate(i),boulders(i))
m3(i,3)=min(culow(i),cddeep(i),boulders(i))
m3(i,4)=min(culow(i),cdshallow(i),fg(i))
m3(i,5)=min(culow(i),cdvdeep(i),ls(i))
m3(i,6)=min(culow(i),cdvshallow(i),boulders(i))
m3(i,7)=min(culow(i),cdvshallow(i),mg(i))
m3(i,8)=min(culow(i),cdmoderate(i),lg(i))
m3(i,9)=min(cuvhigh(i),cdshallow(i),boulders(i))
m3(i,10)=min(cuvhigh(i),cdmoderate(i),boulders(i))
m3(i,11)=min(cuvhigh(i),cdmoderate(i),lg(i))
m3(i,12)=min(cuvlow(i),cddeep(i),boulders(i))
m3(i,13)=min(cuvlow(i),cdshallow(i),sand(i))
m3(i,14)=min(cuvlow(i),cdmoderate(i),fg(i))
m3(i,15)=min(cuvlow(i),cdmoderate(i),ls(i))
m3(i,16)=min(cuvlow(i),cdmoderate(i),sand(i))
m3(i,17)=min(cumoderate(i),cddeep(i),ss(i))
m3(i,18)=min(cumoderate(i),cddeep(i),lg(i))
m3(i,19)=min(cumoderate(i),cdshallow(i),mg(i))
m3(i,20)=min(cumoderate(i),cdmoderate(i),lg(i))
p3(i,1)=min(cuhigh(i),cdmoderate(i),lg(i))
p3(i,2)=min(culow(i),cddeep(i),ss(i))
p3(i,3)=min(culow(i),cdvdeep(i),lg(i))
p3(i,4)=min(cuvhigh(i),cdshallow(i),mg(i))
p3(i,5)=min(cuvhigh(i),cdvshallow(i),fg(i))
p3(i,6)=min(cuvhigh(i),cdvshallow(i),sand(i))
p3(i,7)=min(cuvhigh(i),cdmoderate(i),ss(i))
p3(i,8)=min(cuvlow(i),cddeep(i),ls(i))
p3(i,9)=min(cuvlow(i),cdmoderate(i),mg(i))

high=maxval(h3, dim=2)
good=maxval(g3, dim=2)
moderate=maxval(m3, dim=2)
poor=maxval(p3, dim=2)
bad=maxval(b3, dim=2)
end do

end subroutine sopt
