subroutine swors
use fdeclarations

implicit none

do i=1,n
b2(i,1)=min(culow(i),cdshallow(i),boulders(i))
b2(i,2)=min(cuvhigh(i),cdmoderate(i),boulders(i))
b2(i,3)=min(cuvlow(i),cdvshallow(i),sand(i))
b2(i,4)=min(cuvlow(i),cdmoderate(i),boulders(i))
g2(i,1)=min(cuhigh(i),cdvshallow(i),ls(i))
g2(i,2)=min(cuhigh(i),cdmoderate(i),ls(i))
g2(i,3)=min(cuvlow(i),cdvshallow(i),lg(i))
g2(i,4)=min(cuvlow(i),cdmoderate(i),lg(i))
g2(i,5)=min(cumoderate(i),cdvshallow(i),lg(i))
h2(i,1)=min(cuvhigh(i),cdshallow(i),ss(i))
h2(i,2)=min(cumoderate(i),cdshallow(i),boulders(i))
h2(i,3)=min(cumoderate(i),cdvshallow(i),boulders(i))
m2(i,1)=min(cuhigh(i),cdshallow(i),lg(i))
m2(i,2)=min(cuhigh(i),cdshallow(i),ls(i))
m2(i,3)=min(cuhigh(i),cdvshallow(i),ss(i))
m2(i,4)=min(cuhigh(i),cdmoderate(i),boulders(i))
m2(i,5)=min(cuhigh(i),cdmoderate(i),ss(i))
m2(i,6)=min(culow(i),cddeep(i),boulders(i))
m2(i,7)=min(culow(i),cdshallow(i),mg(i))
m2(i,8)=min(culow(i),cdshallow(i),ss(i))
m2(i,9)=min(culow(i),cdvdeep(i),ls(i))
m2(i,10)=min(culow(i),cdvshallow(i),boulders(i))
m2(i,11)=min(culow(i),cdvshallow(i),ls(i))
m2(i,12)=min(culow(i),cdvshallow(i),mg(i))
m2(i,13)=min(culow(i),cdvshallow(i),ss(i))
m2(i,14)=min(culow(i),cdmoderate(i),boulders(i))
m2(i,15)=min(culow(i),cdmoderate(i),ss(i))
m2(i,16)=min(cuvhigh(i),cdmoderate(i),lg(i))
m2(i,17)=min(cuvlow(i),cdshallow(i),sand(i))
m2(i,18)=min(cuvlow(i),cdvshallow(i),ls(i))
m2(i,19)=min(cuvlow(i),cdmoderate(i),fg(i))
m2(i,20)=min(cuvlow(i),cdmoderate(i),sand(i))
m2(i,21)=min(cumoderate(i),cddeep(i),ss(i))
m2(i,22)=min(cumoderate(i),cddeep(i),lg(i))
m2(i,23)=min(cumoderate(i),cdshallow(i),lg(i))
m2(i,24)=min(cumoderate(i),cdshallow(i),ls(i))
m2(i,25)=min(cumoderate(i),cdshallow(i),mg(i))
m2(i,26)=min(cumoderate(i),cdshallow(i),ss(i))
m2(i,27)=min(cumoderate(i),cdvshallow(i),ss(i))
m2(i,28)=min(cumoderate(i),cdmoderate(i),lg(i))
p2(i,1)=min(cuhigh(i),cdshallow(i),boulders(i))
p2(i,2)=min(cuhigh(i),cdshallow(i),ss(i))
p2(i,3)=min(cuhigh(i),cdmoderate(i),lg(i))
p2(i,4)=min(culow(i),cddeep(i),ss(i))
p2(i,5)=min(culow(i),cdshallow(i),fg(i))
p2(i,6)=min(culow(i),cdshallow(i),lg(i))
p2(i,7)=min(culow(i),cdshallow(i),ls(i))
p2(i,8)=min(culow(i),cdvdeep(i),lg(i))
p2(i,9)=min(culow(i),cdvshallow(i),lg(i))
p2(i,10)=min(culow(i),cdmoderate(i),lg(i))
p2(i,11)=min(culow(i),cdmoderate(i),ls(i))
p2(i,12)=min(cuvhigh(i),cdshallow(i),boulders(i))
p2(i,13)=min(cuvhigh(i),cdshallow(i),lg(i))
p2(i,14)=min(cuvhigh(i),cdshallow(i),ls(i))
p2(i,15)=min(cuvhigh(i),cdshallow(i),mg(i))
p2(i,16)=min(cuvhigh(i),cdvshallow(i),fg(i))
p2(i,17)=min(cuvhigh(i),cdvshallow(i),sand(i))
p2(i,18)=min(cuvhigh(i),cdmoderate(i),ls(i))
p2(i,19)=min(cuvhigh(i),cdmoderate(i),ss(i))
p2(i,20)=min(cuvlow(i),cddeep(i),boulders(i))
p2(i,21)=min(cuvlow(i),cddeep(i),ls(i))
p2(i,22)=min(cuvlow(i),cdshallow(i),boulders(i))
p2(i,23)=min(cuvlow(i),cdshallow(i),fg(i))
p2(i,24)=min(cuvlow(i),cdshallow(i),lg(i))
p2(i,25)=min(cuvlow(i),cdshallow(i),ls(i))
p2(i,26)=min(cuvlow(i),cdshallow(i),mg(i))
p2(i,27)=min(cuvlow(i),cdshallow(i),ss(i))
p2(i,28)=min(cuvlow(i),cdvshallow(i),boulders(i))
p2(i,29)=min(cuvlow(i),cdmoderate(i),ls(i))
p2(i,30)=min(cuvlow(i),cdmoderate(i),mg(i))
p2(i,31)=min(cumoderate(i),cdvshallow(i),ls(i))
p2(i,32)=min(cumoderate(i),cdmoderate(i),ls(i))
p2(i,33)=min(cumoderate(i),cdmoderate(i),ss(i))

high=maxval(h2, dim=2)
good=maxval(g2, dim=2)
moderate=maxval(m2, dim=2)
poor=maxval(p2, dim=2)
bad=maxval(b2, dim=2)
end do

end subroutine swors
